install:
  - if ! pip3 -V ; then wget -O - https://bootstrap.pypa.io/get-pip.py | python3; fi

docker:
  as_root: true
  image: "coala/rultor-python"

merge:
  fast-forward: only
  script:
    - python3 .ci/adjust_version_number.py bears/VERSION -b `date --utc +%Y%m%d%H%M%S`
    - bash .ci/deploy.pypi.sh

release:
  script: bash .ci/release.sh

decrypt:
  rultor_secrets.sh: "repo/.ci/rultor_secrets.sh.asc"
