language:
  # The `objective-c` language by default uses a OSX build container. This
  # is the currently supported method of using a OSX xontainer.
  - objective-c

env:
  global:
    - PYENV_ROOT=~/.pyenv
    - PATH=$PYENV_ROOT/shims:$PATH
  matrix:
    - PYTHON_VERSION=3.4.2

install:
  - bash .ci/deps.osx.sh

script:
  - bash .ci/tests.sh

notifications:
  email: false
